# Generated by Django 5.0.6 on 2024-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('quantidade_portas', models.IntegerField()),
                ('tipo_combustivel', models.CharField(max_length=50)),
                ('ano_carro', models.IntegerField()),
                ('placa', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('valor_comprado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_vendido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
